apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      logging:
        # s3:
        #  aws_region: us-east-1
        #  s3_bucket_name: k8s-opentelemetry-data
        # s3_access_key: AKIA6IWZ6G25T46RELVU
        # s3_secret_key: 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
        #awss3:
        #aws_region: 'us-east-1'
        #aws_access_key_id: 'AKIA6IWZ6G25T46RELVU'
        #aws_secret_access_key: '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'
        #s3_bucket: 'k8s-opentelemetry-data'
        #s3_prefix: 'metric'
        #s3_partition: 'minute'
      jaeger:
          endpoint: "simplest-collector:14250"
          tls:
             insecure: true
               #otlphttp:
               # endpoint: http://loki-stack.default.svc.cluster.local:3100
               #tls:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [jaeger,logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging]


